kind: pipeline
name: demo

steps:
  - name: migrations
      image: flyway/flyway:6.0.6
      commands:
        - "/flyway/flyway migrate"
        -
  - name: mvn clean test
    image: maven:3.6.2-jdk-8
    commands:
      - mvn clean test

services:
  - name: mysql
    image: mysql:5.7.26
    detach: true
    environment:
      MYSQL_ROOT_PASSWORD: r00t
