CREATE SCHEMA IF NOT EXISTS BLESSINGS;
USE BLESSINGS;

CREATE TABLE IF NOT EXISTS `BLESSINGS`.Bless(
    id INTEGER auto_increment PRIMARY KEY,
    message VARCHAR(60) NOT NULL
);

INSERT INTO  `BLESSINGS`.Bless(message) VALUES("Have a nice day"), ("Don't worry, be happy"), ("Today is friday");;

CREATE USER IF NOT EXISTS 'blessUser'@'%' IDENTIFIED BY 'bl355';
GRANT ALL PRIVILEGES ON BLESSINGS.* TO 'blessUser'@'%';
FLUSH PRIVILEGES;
